name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sandhujag/airflow:1.10.12-python3.6-GMF
    
    - name: Docker push
      run: docker push sandhujag/airflow:1.10.12-python3.6-GMF

